### PR TITLE
Deprecate vectorized isna in favor of dot-broadcast

### PR DESCRIPTION
**Pull request by ararslan**
For consistency with Base

### CODE REVIEW

**Comment by nalimilan** [comment]
Could this have caused [this GLM.jl failure](http://pkg.julialang.org/logs/GLM_0.6.log)?
```
  Got an exception of type BoundsError outside of a @test
  BoundsError: attempt to access ()
    at index [1]
  Stacktrace:
   [1] macro expansion at /home/vagrant/.julia/v0.6/DataArrays/src/dataarray.jl:254 [inlined]
   [2] macro expansion at /home/vagrant/.julia/v0.6/Compat/src/ngenerate.jl:60 [inlined]
   [3] isna(::DataArrays.DataArray{Float64,1}) at /home/vagrant/.julia/v0.6/Compat/src/ngenerate.jl:57
   [4] completecases(::DataFrames.DataFrame) at /home/vagrant/.julia/v0.6/DataFrames/src/abstractdataframe/abstractdataframe.jl:471
   [5] na_omit at /home/vagrant/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:235 [inlined]
   [6] #ModelFrame#122(::Dict{Any,Any}, ::Type{T} where T, ::DataFrames.Terms, ::DataFrames.DataFrame) at /home/vagrant/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:320
   [7] (::Core.#kw#Type)(::Array{Any,1}, ::Type{DataFrames.ModelFrame}, ::DataFrames.Terms, ::DataFrames.DataFrame) at ./<missing>:0
   [8] #ModelFrame#125(::Array{Any,1}, ::Type{T} where T, ::DataFrames.Formula, ::DataFrames.DataFrame) at /home/vagrant/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:333
   [9] (::Core.#kw#Type)(::Array{Any,1}, ::Type{DataFrames.ModelFrame}, ::DataFrames.Formula, ::DataFrames.DataFrame) at ./<missing>:0
   [10] #fit#151(::Dict{Any,Any}, ::Array{Any,1}, ::Function, ::Type{GLM.GeneralizedLinearModel}, ::DataFrames.Formula, ::DataFrames.DataFrame, ::Distributions.Poisson{Float64}, ::Vararg{Distributions.Poisson{Float64},N} where N) at /home/vagrant/.julia/v0.6/DataFrames/src/statsmodels/statsmodel.jl:52
   [11] fit(::Type{GLM.GeneralizedLinearModel}, ::DataFrames.Formula, ::DataFrames.DataFrame, ::Distributions.Poisson{Float64}) at /home/vagrant/.julia/v0.6/DataFrames/src/statsmodels/statsmodel.jl:52
```

**Comment by ararslan** [comment]
Seems unlikely. I don't see what in this PR could have changed the behavior that's getting hit here.

**Comment by ararslan** [comment]
Though on the other hand, I don't see anything else in the v0.4.0/v0.5.0 diff that looks any more related to the failure, so...

**Comment by nalimilan** [comment]
Turns out the deprecation wasn't actually used, see https://github.com/JuliaStats/DataArrays.jl/pull/251.

**Pull request merged**
