### PR TITLE
[release-0.4] backport of deprecation fix (#254) and CI updates (#253)

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by ararslan** [comment]
Hmmmmm those CI failures are concerning.

**Comment by tkelman** [comment]
DataArrays has been failing tests on 0.5 on PkgEval all month - http://pkg.julialang.org/detail/DataArrays.html

Let's see if we can dig up what caused it.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9115

**Comment by ararslan** [comment]
Ah! Can you add 36be3152e1ff785ce4015c0218a3a2c29c3e3465 to this as well then?

**Comment by ararslan** [comment]
Oh, hm. That didn't seem to do it.

**Comment by tkelman** [comment]
should track the failure on 0.5 separately, but this isn't making it any worse. can we get the deprecation fix released so `using DataFrames` doesn't warn for everyone?

**Pull request merged**
