### PR TITLE
enable AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**
I think there may be a test failure on Windows at the moment - can someone turn AppVeyor on for this repo on their account? For people with commit access the AppVeyor site should handle enabling the webhook, but if it doesn't work then I can dig up specific instructions.

### CODE REVIEW

**Comment by tkelman** [comment]
```
Running tests:
 * abstractarray.jl
 * booleans.jl
 * constructors.jl
 * containers.jl
 * conversions.jl
 * data.jl
 * dataarray.jl
 * datamatrix.jl
 * indexing.jl
 * linalg.jl
 * nas.jl
 * operators.jl
 * reduce.jl
 * reducedim.jl
 * broadcast.jl
ERROR: LoadError: LoadError: test error in expression: broadcast(+,arr(eye(2)),arr([1,4]))
 == [2 1;4 5]
TypeError: non-boolean (DataArrays.NAtype) used in boolean context
 in do_test at test.jl:51
 in do_test at test.jl:51
while loading C:\Users\Tony\.julia\v0.4\DataArrays\test\broadcast.jl, in expression starti
ng on line 23
while loading C:\Users\Tony\.julia\v0.4\DataArrays\test\runtests.jl, in expression startin
g on line 36
==================================[ ERROR: DataArrays ]===================================


failed process: Process(`'D:\code\Julia-0.4.0-rc3-win64\bin\julia' --check-bounds=yes --co
de-coverage=none --color=yes 'C:\Users\Tony\.julia\v0.4\DataArrays\test\runtests.jl'`, Pro
cessExited(1)) [1]

==========================================================================================

ERROR: DataArrays had test errors
 in test at pkg/entry.jl:753
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

julia> versioninfo()
Julia Version 0.4.0-rc3+43
Commit 125509a* (2015-10-03 05:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.installed("DataArrays")
v"0.2.20"
```

**Comment by nalimilan** [comment]
I've added it to my account: https://ci.appveyor.com/project/nalimilan/dataarrays-jl

**Comment by tkelman** [comment]
There should be a badge markdown example under the settings. There is a generic way of getting the badge url for public github hosted projects but I'll have to look it up when at a computer.

**Comment by tkelman** [comment]
okay looks like the webhook isn't enabled. can you find and copy the webhook url from the settings too? it'll need someone with admin access to edit the webhook

**Comment by nalimilan** [comment]
Yeah, I couldn't find anything to do this automatically. The URL is https://ci.appveyor.com/api/github/webhook?id=ksucug7jix6m53s4 Any owner around?

**Comment by tkelman** [comment]
ref https://github.com/JuliaOpt/JuMP.jl/pull/362#issuecomment-70610293 for what needs to be set on the webhook

**Comment by tkelman** [comment]
cc @simonster can you turn on the webhook here? See the instructions linked above, use the webhook url @nalimilan posted.

**Comment by simonster** [comment]
Done.

**Comment by andreasnoack** [comment]
@nalimilan Can you try to restart the AppVeyor tests here?

**Comment by nalimilan** [comment]
The PR would need to be rebased against master, and 0.3 disabled. @tkelman Would you do that? Or do you prefer me to do it (in another branch)?

**Comment by tkelman** [comment]
rebase isn't strictly necessary since CI runs for PR's on the latest merge commit, but good call on removing 0.3. done.

**Comment by nalimilan** [comment]
Ah, my bad. Thanks for the update. I'll merge it since it's an improvement over the current situation, but we'll have to fix the failure on 32-bit Windows.

**Comment by nalimilan** [comment]
Turns out that failure should be easy to fix: https://github.com/JuliaStats/DataArrays.jl/pull/188.

**Pull request merged**
