### PR TITLE
Fix WeightVec deprecation from StatsBase 0.15

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
Could someone make a branch off of https://github.com/JuliaStats/DataArrays.jl/commit/2a83487bb7cbf570bb6679eb5995ce3545c2869c that supports Julia 0.5 so we could fix this there too?

**Comment by ararslan** [comment]
That commit doesn't support 0.5, unless I'm missing something.

**Comment by tkelman** [comment]
My mistake, copy-pasted the wrong thing. I meant the commit right before it, https://github.com/JuliaStats/DataArrays.jl/commit/2f235b4de970490a75acb970c55cd4660143367a

**Comment by ararslan** [comment]
I assume the deprecation is causing issues on 0.5 in some packages that depend on DataArrays?

**Comment by ararslan** [comment]
A `release-0.3` branch has been made for commits that support Julia 0.5, so we can release more 0.3.x versions from there.

**Comment by ararslan** [comment]
The 32-bit AV commit looks unrelated, but I have absolutely no idea what could be causing it.

**Comment by tkelman** [comment]
It's just introducing depwarn noise on 0.5 that wasn't there before. If the person who introduced that feature doesn't need it on 0.5, maybe it would be better to make that release of StatsBase 0.6-only.

One thing that's a bit annoying is StatsBase 0.15 doesn't support Julia 0.4 but DataArrays 0.3.x did. DataArrays 0.4.0 went straight to 0.6-only so there's no minor release series here that supports Julia 0.5 as a minimum. We could maybe tag it as DataArrays 0.4.1 which would be a bit out of order, or make a versioning exception and do 0.3.13 with a floor of Julia 0.5.

**Comment by ararslan** [comment]
The Julia version jump between tags was out of necessity. Once we figured out how to get DataArrays working on 0.6 at all, we simply weren't able to find a way to support 0.5 and 0.6 at the same time, so we just had to drop everything but 0.6.

I don't know what the best way forward is in terms of backporting this. You know way more about that stuff than I do.

**Comment by tkelman** [comment]
That's fine, but dropping support for 2 release series of Julia should have in retrospect bumped the package minor version twice, to leave a space for 0.5-only backports. If nobody cares much about the 0.4.0 release of DataArrays any more, it may be simplest to release the backport of this as 0.4.1.

**Comment by ararslan** [comment]
So 0.4.0 will be support Julia 0.6 only, but 0.4.1 will support Julia 0.4 and 0.5?

**Comment by tkelman** [comment]
No, DataArrays 0.4.1 would support Julia 0.5 and up (it can't support Julia 0.4 if it wants to depend on StatsBase 0.15, unless we go bring back 0.4 support there). Or just Julia 0.5, but it shouldn't make much difference since DataArrays 0.5.x is available for Julia 0.6.

**Comment by ararslan** [comment]
Okay, sounds good. I've removed `release-0.3` and made a `release-0.4` branch.

**Comment by tkelman** [comment]
Looks like the win32 issue is nightly-only https://ci.appveyor.com/project/nalimilan/dataarrays-jl/build/1.0.223 so that's mostly likely a bug in base julia. Worth attempting to isolate.

**Comment by tkelman** [comment]
Should track the win32 issue separately, but I don't think this is causing it. The user experience of all these warnings is pretty bad, can we can these fixed?

**Comment by ararslan** [comment]
Ah, sorry for the delay, been busy

**Pull request merged**
