### PR TITLE
Add parent field to DataArray

### PR DESCRIPTION
**Pull request by quinnj**
Just like NullableArrays.

### CODE REVIEW

**Comment by quinnj** [comment]
@andreasnoack @nalimilan, any concerns here? This just mirrors what we have in NullableArrays in an effort to make DataArray-backed DataFrames 1st-class in the DataStreams world.

**Comment by andreasnoack** [comment]
Could you explain why this is useful?

**Comment by quinnj** [comment]
The general idea is that if you mmap some data, you have a `Vector{UInt8}` that you need to hold a reference to while your data in the actual `.values` field can reference that memory. The most immediate application is for `WeakRefString` which is just a `Ptr{UInt8}` and `len` into some data.

**Comment by ararslan** [comment]
@simonster Can you explain your 👎?

**Comment by simonster** [comment]
What happens if the DataArray gets garbage-collected but you still have an element from inside of it, and then you try to access that element?

**Comment by quinnj** [comment]
Noodling on this today, I think a good solution might be to define `getindex(A::DataArray{WeakRefString}, i) => String`, i.e. if you pull an individual element out, it converts to a regular string. That would allow us to utilize the performance boosts of WeakRefStrings with more safety.

**Comment by simonster** [comment]
That would be much better in terms of safety, but you'll be allocating every time you take a string out of the array, so the perf improvement may not be so impressive. Also you'd also want to make sure that anything that returns the data field of the DataArray (e.g. `convert(Array, x::DataArray)`) also does it safely.

In general, I think a better way of abstracting this may be to allow DataArrays to wrap arbitrary StridedArrays, and then implement `WeakRefArray{T,N} <: DenseArray{T,N}` and stick the parent field there.

**Comment by nalimilan** [comment]
See previous discussion regarding wrapping arbitrary arrays here: https://github.com/JuliaStats/NullableArrays.jl/issues/112#issuecomment-225365429 What has changed is that we now have triangular dispatch in Julia 0.6.

**Comment by andreasnoack** [comment]
> What has changed is that we now have triangular dispatch in Julia 0.6.

Even without that, it doesn't look like the problem here is any different from any of the other wrapper `AbstractArray` types we have had for a long time. It requires some care in the constructors but it seems to work well. I'd prefer allowing the values to be any `AbstractArray`.

**Pull request closed without merging**
