### PR TITLE
Replace array with Base.convert

### PR DESCRIPTION
**Pull request by yesimon**
This is just a rebased change from #108. Moved `array()` stuff into deprecated but otherwise didn't change the PR.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
+1

**Comment by simonster** [comment]
It looks like the deprecated functions are still in `dataarray.jl` and `pooleddataarray.jl`. Maybe you missed a commit? Other than that, I think this should be good to go.

**Comment by yesimon** [comment]
Fixed

**Comment by simonster** [comment]
Thanks!

**Comment by garborg** [comment]
Fine if I tag this, so I can start using this with DataFrames (and remove warnings from internal DataFrames code)?

**Comment by simonster** [comment]
Fine with me.

**Comment by garborg** [comment]
Thanks. Tagged and released.

**Comment by garborg** [comment]
Thoughts?:

```julia
julia> using DataArrays

julia> dv = @data([NA, 3, 2, 5, 4])
5-element DataArrays.DataArray{Int64,1}:
  NA
 3
 2
 5
 4

julia> convert(Array, dv, 11)
5-element Array{Int64,1}:
 11
  3
  2
  5
  4

julia> convert(Matrix, dv, 11)
ERROR: MethodError: `convert` has no method matching convert(::Type{Array{T,2}}, ::DataArrays.DataArray{Int64,1}, ::Int64)
This may have arisen from a call to the constructor Array{T,2}(...),
since type constructors fall back to convert methods.
```

**Comment by simonster** [comment]
Maybe I'm missing the point, but since `convert(Matrix, ::Vector)` doesn't work, I wouldn't expect `convert(Matrix, ::DataVector)` to work either.

**Comment by garborg** [comment]
You're right, I thought it did but didn't check.

**Pull request merged**
