### PR TITLE
[rs] is deprecated, use [rs...] instead

### PR DESCRIPTION
**Pull request by gustafsson**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
I suspect this should use `collect(rs)` to avoid a tuple-splitting penalty.

**Comment by gustafsson** [comment]
@johnmyleswhite sure, that makes sense

@nalimilan did you change your opinion on `[a...]` vs `collect(a)`? https://github.com/JuliaStats/DataFrames.jl/pull/944

**Comment by nalimilan** [comment]
> @nalimilan did you change your opinion on [a...] vs collect(a)? JuliaStats/DataFrames.jl#944

Not really. In the present case, splatting might involve thousands of values (think of `1:1000`), which will be very costly for the compiler. In the other issue, splatting only involved a few arguments which were already passed as varargs, so a method was compiled for each number of arguments anyway.

**Comment by ararslan** [comment]
This looks good to me.

**Comment by gustafsson** [comment]
@nalimilan I see, thanks for the explanation

**Comment by nalimilan** [comment]
Thanks!

**Pull request merged**
