### PR TITLE
WIP: Deprecations and updates for consistency with Base

### LINKED ISSUE #239: Things we should deprecate for consistency with Base
In the interest of having an API consistent with that of Base, I think we should deprecate the following methods:

- [ ] `DataArray(T, ...)` in favor of `DataArray{T}(...)` (likewise for `PooledDataArray`)
- [ ] Elementwise `isna(X)` in favor of dot-broadcast `isna.(X)`
- [ ] `NAtype` in favor of `NAType` (upper camel case preferred for type names)
- [ ] Elementwise `allna(x)` -> `all(isna, x)`
- [ ] Elementwise `anyna(x)` -> `any(isna, x)`
- [ ] `padNA` -> `padna`, mostly for self-consistency

These functions don't really seem to belong here:

- [ ] `xtab` and `xtabs` -- functionality provided by FreqTables
- [ ] `reldiff` and `percent_change` -- not specific to `DataArray`s and apparently untested

Functions that could use more descriptive names:

- [ ] `gl` (may not belong here though a case could be made)

Thoughts?

### PR DESCRIPTION
**Pull request by ararslan**
This implements the following changes:

- [ ] ~~Deprecate `NAtype` in favor of `NAType`~~
- [x] Deprecate `anyna(x)` in favor of `any(isna, x)` (likewise for `all`)
- [x] Deprecate vectorized `isna` in favor of dot-broadcast
- [ ] ~~Convert tests to use `@testset`s rather than modules~~ (separate PR)
- [ ] ~~Convert tests to use `@test` instead of `@assert`~~ (separate PR)
- [x] Deprecate `reldiff`, `percent_change`, `xtab`, and `xtabs`
- [x] Deprecate `DataArray(T, dims)` constructors in favor of `DataArray{T}(dims)`
- [ ] Likewise for `PooledDataArray`

Fixes #239.

### CODE REVIEW

**Comment by nalimilan** [comment]
+1 except for renaming `NAtype`. This sounds like unnecessary churn given that we're likely to change this more deeply with the new `Union` optimization in Base. Better not waste people's time.

**Comment by ararslan** [comment]
Okay, that's fine with me. It's just a pet peeve of mine but you're right that it's probably not worth pursuing.

**Comment by ararslan** [comment]
Ugh, this is kind of a mess and I've lost track of my progress. An unfortunate example of PR scope creep. I think I'll separate this into a few PRs. That should make it easier for all involved.

**Comment by ararslan** [comment]
Forgot to close this. I'm breaking the changes into multiple PRs. Thanks for taking a look at this, Milan.

**Pull request closed without merging**
