### PR TITLE
Update tests to use testsets

### PR DESCRIPTION
**Pull request by ararslan**
This PR restructures the tests to use `@testset` and `@test` rather than wrapping units of tests in modules and checking correctness with `@assert`.

### CODE REVIEW

**Comment by nalimilan** [comment]
Are the failures expected?

**Comment by ararslan** [comment]
Expected? Not entirely. I may have done some bad find-and-replaces, or turned things into `@test`s when they shouldn't have been. Will look more at this in a bit.

**Comment by ararslan** [comment]
Turns out the failures are macro things that don't like being in `@testset`s. Moving macro definitions outside and not using `@eval` in a macro in a macro seems to help.

**Comment by ararslan** [comment]
Okay, failures are all fixed. The commits should be squashed on merge. I welcome anyone to take a look.

**Comment by nalimilan** [comment]
I've only skimmed the changes, but this looks good to me as long as you only moved existing tests (I would have a hard time spotting subtle changes inside the diff!).

**Comment by ararslan** [comment]
Yeah, the diff is a bit of a beast. Yes, I only moved existing tests; there should be no functional changes, just nicer test output. Thanks for taking a look!

**Pull request merged**
