### PR TITLE
Update predicates.jl for function isprime()

### PR DESCRIPTION
**Pull request by colbec**
isprime() has been moved to Primes from Base.
Ref: https://github.com/JuliaStats/DataArrays.jl/issues/226

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but you also need to add Primes.jl to `REQUIRE` and add a `import` call.

**Comment by colbec** [comment]
Thanks, I needed the guidance. I have replaced my `using` statement with an `import`, and tried to update the `REQUIRE`.

**Comment by ararslan** [comment]
I don't think we need Primes.jl here at all. It seems to me it would be sufficient to do:
```julia
numeric_predicates = [:(Base.iseven), :(Base.ispow2), :(Base.isfinite), :(Base.isinf), :(Base.isodd))]
isdefined(Base, :isprime) && push!(numeric_predicates, :(Base.isprime))
```

**Comment by colbec** [comment]
I'm happy to yield to a better solution @ararslan . My suggestion was just a starting point.

**Comment by ararslan** [comment]
If you'd be willing to use the code I posted in my comment above, I think that should do it. Thanks for your help here!

**Comment by colbec** [comment]
I think the code offered by @ararslan is working, but there is a new error 

> no method matching size(::Type{DataArrays.DataArray})

In addition it would be really helpful to eliminate the large numbers of warnings related to broadcast functions.

**Comment by nalimilan** [comment]
Honestly, I'm not sure somebody is going to do the work of fixing all the deprecations. We have already a lot of work to do to replace DataArrays with NullableArrays, so 0.5 might well be the last Julia release where the former will work without deprecation warnings. Fixing the error in `broadcast` would already be great.

**Pull request merged**
